[workspace]
members = [
  ".",
  "actors/builder",
  "actors/canon",
  "actors/gc",
  "actors/pending",
  "actors/rpc",
  "actors/reputation",
  "actors/sim",
  "actors/engine-api",
  "actors/shared",
  "actors/beacon",
]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2024"
rust-version = "1.87"
license = "MIT"
homepage = "https://github.com/flashbots/mosaik"
repository = "https://github.com/flashbots/mosaik"
authors = ["Flashbots <info@flashbots.net>", "Karim Agha <karim@flashbots.net>"]
exclude = [".github/"]

[workspace.lints.rust]
type_alias_bounds = "allow"
#unreachable_pub = "deny"

[workspace.lints.clippy]
tabs_in_doc_comments = "allow"
pedantic = { level = "warn", priority = -1 }
wildcard_imports = "allow"
missing_errors_doc = "allow"
must_use_candidate = "allow"
redundant_closure_for_method_calls = "allow"
similar_names = "allow"
cast_precision_loss = "allow"
unused_async = "warn"

[workspace.metadata.scripts]
lint = "cargo clippy --all-targets -- -D warnings"

[workspace.dependencies]
mosaik = { path = "." }
rblib = { git = "https://github.com/flashbots/rblib.git", tag = "v0.4.0", features = [
] }
engine-api = { path = "actors/engine-api" }

rand = "0.9"
anyhow = "1.0"
thiserror = "2.0"
serde = "1.0.228"
bincode = { version = "2.0", features = ["serde"] }
rmp-serde = "1.3.0"
futures = "0.3"
bytes = "1.10"
data-encoding = "2.9"
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.48", features = ["full"] }
tokio-util = "0.7"
tokio-stream = "0.1"
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

iroh = { version = "0.95", features = ["discovery-local-network"] }
iroh-gossip = "0.95"
iroh-blobs = "0.97"
iroh-docs = "0.95"
n0-error = "0.1"

[package]
name = "mosaik"
description = "Distributed Order Pool Fabric"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
exclude.workspace = true

[lints]
workspace = true

[[bin]]
name = "mosaik"
required-features = ["cli"]

[features]
cli = ["clap", "tracing-subscriber"]

[dependencies]
futures.workspace = true
tokio.workspace = true
tokio-util.workspace = true
serde.workspace = true
bincode.workspace = true
rmp-serde.workspace = true
bytes.workspace = true
iroh.workspace = true
iroh-gossip.workspace = true
anyhow.workspace = true
rand.workspace = true
chrono.workspace = true
tracing.workspace = true
thiserror.workspace = true
tokio-stream.workspace = true
n0-error.workspace = true

derive_more = { version = "2.1", features = ["full"] }
blake3 = { version = "1.8", features = ["serde"] }
hmac = "0.12"
hex = "0.4"
im = { version = "15.1.0", features = ["serde"] }
parking_lot = "0.12"
semver = { version = "1.0", features = ["serde"] }
dashmap = "6.1"
slotmap = "1.1"
derive_builder = "0.20.2"
backoff = { version = "0.4", features = ["futures", "tokio"] }
humansize = "2.0.0"
humantime = "2.3"

# CLI only dependencies
clap = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }

[dev-dependencies]
rblib = { workspace = true, features = ["test-utils"] }
tracing-subscriber = { workspace = true }
ctor = { version = "0.6" }
