[workspace]
members = [".", "examples/orderbook"]
resolver = "2"

[package]
name = "mosaik"
description = "A Rust runtime for building self-organizing, leaderless distributed systems."
version = "0.2.2"
edition = "2024"
rust-version = "1.89"
license = "MIT"
homepage = "https://github.com/flashbots/mosaik"
repository = "https://github.com/flashbots/mosaik"
authors = ["Flashbots <info@flashbots.net>", "Karim Agha <karim@flashbots.net>"]
exclude = [".github/"]

[lib]
doctest = false

[lints.rust]
type_alias_bounds = "allow"

[lints.clippy]
tabs_in_doc_comments = "allow"
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
wildcard_imports = "allow"
missing_errors_doc = "allow"
must_use_candidate = "allow"
redundant_closure_for_method_calls = "allow"
similar_names = "allow"
cast_precision_loss = "allow"
cast_possible_truncation = "allow"
unused_async = "warn"

[dependencies]
rand = "0.9.2"
thiserror = "2.0"
serde = "1.0.228"
postcard = "1.1.3"
futures = "0.3"
bytes = "1.10"
tokio = { version = "1.48", features = ["full"] }
tokio-util = "0.7"
tokio-stream = "0.1"
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
n0-error = "0.1.3"
derive_more = { version = "2.1", features = ["full"] }
blake3 = { version = "1.8", features = ["serde"] }
hex = "0.4"
im = { version = "15.1.0", features = ["serde"] }
semver = { version = "1.0", features = ["serde"] }
dashmap = "6.1"
slotmap = "1.1"
derive_builder = "0.20.2"
backoff = { version = "0.4", features = ["futures", "tokio"] }
humansize = "2.0.0"
humantime = "2.3"
itertools = "0.14"
iroh = { version = "0.96.1", features = [
  "address-lookup-pkarr-dht",
  "address-lookup-mdns",
] }
iroh-gossip = "0.96.0"

[dev-dependencies]
anyhow = "1.0"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
ctor = { version = "0.6" }
rstest = "0.26"
