[workspace]
members = [
  ".",
  "actors/builder",
  "actors/canon",
  "actors/gc",
  "actors/pending",
  "actors/rpc",
  "actors/reputation",
  "actors/sim",
  "actors/engine-api",
  "actors/model",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.87"
license = "MIT"
homepage = "https://github.com/flashbots/mosaik"
repository = "https://github.com/flashbots/mosaik"
authors = ["Flashbots <info@flashbots.net>", "Karim Agha <karim@flashbots.net>"]
exclude = [".github/"]

[workspace.lints.rust]
type_alias_bounds = "allow"

[workspace.lints.clippy]
tabs_in_doc_comments = "allow"
pedantic = { level = "warn", priority = -1 }
wildcard_imports = "allow"
missing_errors_doc = "allow"
must_use_candidate = "allow"
redundant_closure_for_method_calls = "allow"
similar_names = "allow"
cast_precision_loss = "allow"

[workspace.metadata.scripts]
lint = "cargo clippy --all-targets -- -D warnings"

[workspace.dependencies]
mosaik = { path = "." }
rblib = { git = "https://github.com/flashbots/rblib.git", tag = "v0.4.0", features = [
] }
engine-api = { path = "actors/engine-api" }

rand = "0.9"
anyhow = "1.0"
thiserror = "2.0"
serde = "1.0.228"
rmp-serde = "1.3.0"
futures = "0.3"
bytes = "1.10"
data-encoding = "2.9"
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.48", features = ["full"] }
tokio-util = "0.7"
tokio-stream = "0.1"
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

iroh = "0.94"
iroh-gossip = "0.94"
iroh-blobs = "0.96"
iroh-docs = "0.94"

[package]
name = "mosaik"
description = "Distributed Order Pool Fabric"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
exclude.workspace = true

[features]
test-utils = ["tracing-subscriber", "ctor"]

[dependencies]
futures.workspace = true
tokio.workspace = true
tokio-util.workspace = true
serde.workspace = true
rmp-serde.workspace = true
bytes.workspace = true
iroh.workspace = true
iroh-gossip.workspace = true
anyhow.workspace = true
rand.workspace = true
chrono.workspace = true
tracing.workspace = true
thiserror.workspace = true
tokio-stream.workspace = true

derive_more = "2.0"
sha3 = "0.10"
hmac = "0.12"
hex = "0.4"
im = { version = "15.1.0", features = ["serde"] }
parking_lot = "0.12"
semver = { version = "1.0", features = ["serde"] }
dashmap = "6.1"
strum = { version = "0.27", features = ["derive"] }
slotmap = "1.0"
paste = "1.0"

# optional dependencies for testing
tracing-subscriber = { workspace = true, optional = true }
ctor = { version = "0.6", optional = true }


[dev-dependencies]
mosaik = { workspace = true, features = ["test-utils"] }
